export const data = [
  { id: "0", image: require("../../assets/1a.jpg"), name: "Burgers" },
  { id: "1", image: require("../../assets/2a.jpg"), name: "Pizza" },
  { id: "2", image: require("../../assets/4a.jpg"), name: "Fries" },
  { id: "3", image: require("../../assets/3.jpg"), name: "Leg" },
  { id: "4", image: require("../../assets/3a.jpg"), name: "Fish" },
  { id: "5", image: require("../../assets/7a.jpg"), name: "fingerfris" },
  { id: "6", image: require("../../assets/5a.jpg"), name: "Swarma" },
];

export const foodCardData = [
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/3.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 0,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/2.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 1,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/1.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 2,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/4.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 3,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/5.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 4,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/6.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 5,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/5.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 6,
  },
];
